//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePharm.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class drugs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public drugs()
        {
            this.sells = new HashSet<sells>();
            this.usersCart = new HashSet<usersCart>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public bool isNeedPrescription { get; set; }
        public int typeId { get; set; }
        public decimal cost { get; set; }
        public string image { get; set; }
        public string description { get; set; }
    
        public virtual drugTypes drugTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sells> sells { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usersCart> usersCart { get; set; }
    }
}
